### ISSUE TITLE
Spritbatch rendert nicht richtig.

### ISSUE THREAD

**Issue by CsharpLassi** [OctoAwesome/engenious#12]
Hallo,

der Spritbatch rendert falsch bei der Überladung mit Source- und DestinationRectangle.
Beim Source Rectagle wird immer von der Koordinate Y= 0 ausgegangen.

viele grüße
Lassi

**Comment by jvbsl** [comment]
ich hab keine Ahnung wie du das meinst, kannst das vlt. irwie mit Paint illustrieren?

**Comment by CsharpLassi** [comment]
Welche Methode ich meine weißt du oder ???

Also ich möchte das rote Rendern und das gelbe wird gerendert. und so geht es überall. Nur das oberste Tile wird gerendert.
`
![bug](https://cloud.githubusercontent.com/assets/12987399/21485952/04e588a0-cbac-11e6-9c1e-df8371ba0578.png)
`

**Comment by jvbsl** [comment]
Ahh ich glaube es liegt daran, dass ich hier nen float cast vergessen hab
https://github.com/OctoAwesome/engenious/blob/develop/engenious/Graphics/SpriteBatcher.cs#L97

**Comment by CsharpLassi** [comment]
jep sieht so aus

**Comment by fnawratil** [comment]
Sollte damit ja gefixt sein, oder?
