### ISSUE TITLE
SharpFont - BadImageFormat

### ISSUE THREAD

**Issue by fnawratil** [OctoAwesome/engenious#2]
Ich hab das ganze mal auf meinem Surface ausprobiert, bekomme aber immer eine Exception...

Die NuGet Packages wurden wiederhergestellt, die DLL befindet sich im angebenen Ordner...
![6ywsdn](https://cloud.githubusercontent.com/assets/10145306/19028803/65855b26-8940-11e6-9bc1-7dc18cefaa07.png)

**Comment by fnawratil** [comment]
Problem scheint mit der .Net Framework Version zusammenzuhängen...

**Comment by jvbsl** [comment]
ists denn WinRT?

**Comment by fnawratil** [comment]
Nein, windows 10 pro, 64 bit, build 1607
